{
    'DNP': 'A', 'ABI': 'A', 'ALM': 'A', 'MAA': 'A', 'TIH': 'A', 'FLA': 'A', 'DAL': 'A', 'CSD': 'A',
    'BNN': 'A', 'HAC': 'A', 'PRR': 'A', 'AYA': 'A', 'CHG': 'A', 'DHA': 'A', 'TPQ': 'A', 'SEG': 'A',
    'DIV': 'V', 'MVA': 'V', 'DVA': 'V',
    'BUG': 'L', 'DLE': 'L', 'CLE': 'L', 'NLN': 'L', 'NLE': 'L', 'NLP': 'L', 'MLE': 'L', 'LEF': 'L',
    'DIL': 'I', 'IIL': 'I',
    'DPR': 'P', 'HYP': 'P',
    'MSE': 'M', 'OMT': 'M', 'CXM': 'M', 'FME': 'M', 'MME': 'M',
    'DAH': 'F', 'PHI': 'F', 'DPN': 'F', 'HPQ': 'F', 'PHL': 'F',
    'LTR': 'W', 'TPL': 'W', 'DTR': 'W', 'TRO': 'W', 'HTR': 'W',
    'MSA': 'G', 'SAR': 'G', 'MPQ': 'G', 'GLZ': 'G', 'GSC': 'G', 'GL3': 'G', 'NMC': 'G',
    'DSN': 'S', 'SEL': 'S', 'SEP': 'S', 'SET': 'S', 'SAC': 'S', 'SVA': 'S', 'MIS': 'S', 'OAS': 'S',
    'TPO': 'T', 'ALO': 'T', 'DTH': 'T', 'BMT': 'T',
    'BCS': 'C', 'SOC': 'C', 'C5C': 'C', 'C6C': 'C', 'SCS': 'C', 'PEC': 'C', 'DCY': 'C', 'EFC': 'C',
    'SCY': 'C', 'SMC': 'C', 'CSX': 'C', 'BUC': 'C', 'CSO': 'C', 'PR3': 'C', 'CCS': 'C', 'CEA': 'C', 'CME': 'C',
    'CSP': 'C', 'CSS': 'C', 'CSW': 'C', 'CY1': 'C', 'CY3': 'C', 'CYG': 'C', 'CYM': 'C', 'CYQ': 'C', 'SCH': 'C',
    'SHC': 'C', 'OCS': 'C', 'CAS': 'C',
    'TYQ': 'Y', 'TYS': 'Y', 'TYB': 'Y', 'STY': 'Y', 'DTY': 'Y', 'IYR': 'Y', 'PAQ': 'Y', 'TYY': 'Y',
    'PTR': 'Y', 'TYI': 'Y',
    'MEN': 'N',
    'DGN': 'Q', 'MGN': 'Q',
    '2AS': 'D', 'ASB': 'D', 'DAS': 'D', 'ASK': 'D', 'ASL': 'D', 'ASQ': 'D', 'BHD': 'D', 'ASA': 'D',
    'DSP': 'D',
    '5HP': 'E', 'CGU': 'E', 'DGL': 'E', 'GMA': 'E', 'GGL': 'E', 'PCA': 'E',
    'DLY': 'K', 'LYM': 'K', 'LLY': 'K', 'LYZ': 'K', 'KCX': 'K', 'LLP': 'K', 'TRG': 'K', 'SHR': 'K',
    'ALY': 'K',
    'ARM': 'R', 'ACL': 'R', 'HAR': 'R', 'HMR': 'R', 'AGM': 'R', 'DAR': 'R',
    'HIC': 'H', '3AH': 'H', 'NEM': 'H', 'NEP': 'H', 'DHI': 'H', 'MHS': 'H', 'HIP': 'H', 
'ILE': 'I', 'GLN': 'Q',
    'GLX': 'Z', 'GLY': 'G',
    'GLU': 'E', 'CYS': 'C',
    'HIS': 'H', 'SER': 'S',
    'LYS': 'K', 'PRO': 'P',
    'ASX': 'B', 'ASN': 'N',
    'VAL': 'V', 'THR': 'T',
    'ASP': 'D', 'TRP': 'W',
    'PHE': 'F', 'ALA': 'A',
    'MET': 'M', 'LEU': 'L',
    'ARG': 'R', 'TYR': 'Y'}
